version: '3'

includes:
  server:
    taskfile: ./taskfiles/Server.yml
  client:
    taskfile: ./taskfiles/Client.yml

tasks:
  gen:proto:
    desc: Generate proto
    vars:
      PROTO_PATH: internal/common/grpc/proto
    cmds:
      - (cd {{.PROTO_PATH}};protoc --go_out=gen --go_opt=paths=source_relative --go-grpc_out=gen --go-grpc_opt=paths=source_relative --go_opt=default_api_level=API_OPAQUE *.proto)

  build:
    desc: Build apps
    run: once
    cmds:
      - task: client:build
      - task: server:build

  test:
    desc: Run tests
    cmds:
      - go test ./...
