version: '3'

includes:
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server

vars:
  MODULES: [ client, proto, server ]

tasks:
  gen:
    desc: Run gen for all modules
    cmds:
      - for: { var: MODULES }
        task: '{{.ITEM}}:gen'

  test:
    desc: Run tests for all modules
    cmds:
      - for: { var: MODULES }
        cmd: cd {{.ITEM}} && go test ./... {{.CLI_ARGS}}

  tidy:
    desc: Run `go mod tidy` for all modules
    cmds:
      - for: { var: MODULES }
        cmd: cd {{.ITEM}} && go mod tidy