// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/mkolibaba/gophkeeper/server"
	"sync"
)

// Ensure, that BinaryServiceMock does implement server.BinaryService.
// If this is not the case, regenerate this file with moq.
var _ server.BinaryService = &BinaryServiceMock{}

// BinaryServiceMock is a mock implementation of server.BinaryService.
//
//	func TestSomethingThatUsesBinaryService(t *testing.T) {
//
//		// make and configure a mocked server.BinaryService
//		mockedBinaryService := &BinaryServiceMock{
//			CreateFunc: func(ctx context.Context, data server.ReadableBinaryData) error {
//				panic("mock out the Create method")
//			},
//			GetFunc: func(ctx context.Context, id int64) (*server.ReadableBinaryData, error) {
//				panic("mock out the Get method")
//			},
//			GetAllFunc: func(ctx context.Context) ([]server.BinaryData, error) {
//				panic("mock out the GetAll method")
//			},
//			RemoveFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Remove method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, data server.BinaryDataUpdate) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedBinaryService in code that requires server.BinaryService
//		// and then make assertions.
//
//	}
type BinaryServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, data server.ReadableBinaryData) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id int64) (*server.ReadableBinaryData, error)

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]server.BinaryData, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, id int64) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, data server.BinaryDataUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data server.ReadableBinaryData
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Data is the data argument value.
			Data server.BinaryDataUpdate
		}
	}
	lockCreate sync.RWMutex
	lockGet    sync.RWMutex
	lockGetAll sync.RWMutex
	lockRemove sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *BinaryServiceMock) Create(ctx context.Context, data server.ReadableBinaryData) error {
	callInfo := struct {
		Ctx  context.Context
		Data server.ReadableBinaryData
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, data)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedBinaryService.CreateCalls())
func (mock *BinaryServiceMock) CreateCalls() []struct {
	Ctx  context.Context
	Data server.ReadableBinaryData
} {
	var calls []struct {
		Ctx  context.Context
		Data server.ReadableBinaryData
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *BinaryServiceMock) Get(ctx context.Context, id int64) (*server.ReadableBinaryData, error) {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	if mock.GetFunc == nil {
		var (
			readableBinaryDataOut *server.ReadableBinaryData
			errOut                error
		)
		return readableBinaryDataOut, errOut
	}
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedBinaryService.GetCalls())
func (mock *BinaryServiceMock) GetCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *BinaryServiceMock) GetAll(ctx context.Context) ([]server.BinaryData, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	if mock.GetAllFunc == nil {
		var (
			binaryDatasOut []server.BinaryData
			errOut         error
		)
		return binaryDatasOut, errOut
	}
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedBinaryService.GetAllCalls())
func (mock *BinaryServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *BinaryServiceMock) Remove(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	if mock.RemoveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RemoveFunc(ctx, id)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedBinaryService.RemoveCalls())
func (mock *BinaryServiceMock) RemoveCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *BinaryServiceMock) Update(ctx context.Context, id int64, data server.BinaryDataUpdate) error {
	callInfo := struct {
		Ctx  context.Context
		ID   int64
		Data server.BinaryDataUpdate
	}{
		Ctx:  ctx,
		ID:   id,
		Data: data,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, id, data)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedBinaryService.UpdateCalls())
func (mock *BinaryServiceMock) UpdateCalls() []struct {
	Ctx  context.Context
	ID   int64
	Data server.BinaryDataUpdate
} {
	var calls []struct {
		Ctx  context.Context
		ID   int64
		Data server.BinaryDataUpdate
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
