// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/mkolibaba/gophkeeper/server"
	"sync"
)

// Ensure, that NoteServiceMock does implement server.NoteService.
// If this is not the case, regenerate this file with moq.
var _ server.NoteService = &NoteServiceMock{}

// NoteServiceMock is a mock implementation of server.NoteService.
//
//	func TestSomethingThatUsesNoteService(t *testing.T) {
//
//		// make and configure a mocked server.NoteService
//		mockedNoteService := &NoteServiceMock{
//			CreateFunc: func(ctx context.Context, data server.NoteData) error {
//				panic("mock out the Create method")
//			},
//			GetAllFunc: func(ctx context.Context) ([]server.NoteData, error) {
//				panic("mock out the GetAll method")
//			},
//			RemoveFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Remove method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, data server.NoteDataUpdate) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedNoteService in code that requires server.NoteService
//		// and then make assertions.
//
//	}
type NoteServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, data server.NoteData) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]server.NoteData, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, id int64) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, data server.NoteDataUpdate) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data server.NoteData
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Data is the data argument value.
			Data server.NoteDataUpdate
		}
	}
	lockCreate sync.RWMutex
	lockGetAll sync.RWMutex
	lockRemove sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *NoteServiceMock) Create(ctx context.Context, data server.NoteData) error {
	callInfo := struct {
		Ctx  context.Context
		Data server.NoteData
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, data)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedNoteService.CreateCalls())
func (mock *NoteServiceMock) CreateCalls() []struct {
	Ctx  context.Context
	Data server.NoteData
} {
	var calls []struct {
		Ctx  context.Context
		Data server.NoteData
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *NoteServiceMock) GetAll(ctx context.Context) ([]server.NoteData, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	if mock.GetAllFunc == nil {
		var (
			noteDatasOut []server.NoteData
			errOut       error
		)
		return noteDatasOut, errOut
	}
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedNoteService.GetAllCalls())
func (mock *NoteServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *NoteServiceMock) Remove(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	if mock.RemoveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RemoveFunc(ctx, id)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedNoteService.RemoveCalls())
func (mock *NoteServiceMock) RemoveCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *NoteServiceMock) Update(ctx context.Context, id int64, data server.NoteDataUpdate) error {
	callInfo := struct {
		Ctx  context.Context
		ID   int64
		Data server.NoteDataUpdate
	}{
		Ctx:  ctx,
		ID:   id,
		Data: data,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, id, data)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedNoteService.UpdateCalls())
func (mock *NoteServiceMock) UpdateCalls() []struct {
	Ctx  context.Context
	ID   int64
	Data server.NoteDataUpdate
} {
	var calls []struct {
		Ctx  context.Context
		ID   int64
		Data server.NoteDataUpdate
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
