// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/mkolibaba/gophkeeper/proto/gen/go/gophkeeperv1"
	"google.golang.org/grpc"
	"sync"
)

// Ensure, that AuthorizationServiceClientForMockingMock does implement AuthorizationServiceClientForMocking.
// If this is not the case, regenerate this file with moq.
var _ AuthorizationServiceClientForMocking = &AuthorizationServiceClientForMockingMock{}

// AuthorizationServiceClientForMockingMock is a mock implementation of AuthorizationServiceClientForMocking.
//
//	func TestSomethingThatUsesAuthorizationServiceClientForMocking(t *testing.T) {
//
//		// make and configure a mocked AuthorizationServiceClientForMocking
//		mockedAuthorizationServiceClientForMocking := &AuthorizationServiceClientForMockingMock{
//			AuthorizeFunc: func(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error) {
//				panic("mock out the Authorize method")
//			},
//			RegisterFunc: func(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error) {
//				panic("mock out the Register method")
//			},
//		}
//
//		// use mockedAuthorizationServiceClientForMocking in code that requires AuthorizationServiceClientForMocking
//		// and then make assertions.
//
//	}
type AuthorizationServiceClientForMockingMock struct {
	// AuthorizeFunc mocks the Authorize method.
	AuthorizeFunc func(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Authorize holds details about calls to the Authorize method.
		Authorize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *gophkeeperv1.UserCredentials
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *gophkeeperv1.UserCredentials
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockAuthorize sync.RWMutex
	lockRegister  sync.RWMutex
}

// Authorize calls AuthorizeFunc.
func (mock *AuthorizationServiceClientForMockingMock) Authorize(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error) {
	callInfo := struct {
		Ctx  context.Context
		In   *gophkeeperv1.UserCredentials
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockAuthorize.Lock()
	mock.calls.Authorize = append(mock.calls.Authorize, callInfo)
	mock.lockAuthorize.Unlock()
	if mock.AuthorizeFunc == nil {
		var (
			tokenResponseOut *gophkeeperv1.TokenResponse
			errOut           error
		)
		return tokenResponseOut, errOut
	}
	return mock.AuthorizeFunc(ctx, in, opts...)
}

// AuthorizeCalls gets all the calls that were made to Authorize.
// Check the length with:
//
//	len(mockedAuthorizationServiceClientForMocking.AuthorizeCalls())
func (mock *AuthorizationServiceClientForMockingMock) AuthorizeCalls() []struct {
	Ctx  context.Context
	In   *gophkeeperv1.UserCredentials
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *gophkeeperv1.UserCredentials
		Opts []grpc.CallOption
	}
	mock.lockAuthorize.RLock()
	calls = mock.calls.Authorize
	mock.lockAuthorize.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *AuthorizationServiceClientForMockingMock) Register(ctx context.Context, in *gophkeeperv1.UserCredentials, opts ...grpc.CallOption) (*gophkeeperv1.TokenResponse, error) {
	callInfo := struct {
		Ctx  context.Context
		In   *gophkeeperv1.UserCredentials
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	if mock.RegisterFunc == nil {
		var (
			tokenResponseOut *gophkeeperv1.TokenResponse
			errOut           error
		)
		return tokenResponseOut, errOut
	}
	return mock.RegisterFunc(ctx, in, opts...)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedAuthorizationServiceClientForMocking.RegisterCalls())
func (mock *AuthorizationServiceClientForMockingMock) RegisterCalls() []struct {
	Ctx  context.Context
	In   *gophkeeperv1.UserCredentials
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *gophkeeperv1.UserCredentials
		Opts []grpc.CallOption
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}
