// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/mkolibaba/gophkeeper/client"
	"sync"
)

// Ensure, that LoginServiceMock does implement client.LoginService.
// If this is not the case, regenerate this file with moq.
var _ client.LoginService = &LoginServiceMock{}

// LoginServiceMock is a mock implementation of client.LoginService.
//
//	func TestSomethingThatUsesLoginService(t *testing.T) {
//
//		// make and configure a mocked client.LoginService
//		mockedLoginService := &LoginServiceMock{
//			GetAllFunc: func(ctx context.Context) ([]client.LoginData, error) {
//				panic("mock out the GetAll method")
//			},
//			RemoveFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Remove method")
//			},
//			SaveFunc: func(ctx context.Context, data client.LoginData) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedLoginService in code that requires client.LoginService
//		// and then make assertions.
//
//	}
type LoginServiceMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]client.LoginData, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, id int64) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, data client.LoginData) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data client.LoginData
		}
	}
	lockGetAll sync.RWMutex
	lockRemove sync.RWMutex
	lockSave   sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *LoginServiceMock) GetAll(ctx context.Context) ([]client.LoginData, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	if mock.GetAllFunc == nil {
		var (
			loginDatasOut []client.LoginData
			errOut        error
		)
		return loginDatasOut, errOut
	}
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedLoginService.GetAllCalls())
func (mock *LoginServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *LoginServiceMock) Remove(ctx context.Context, id int64) error {
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	if mock.RemoveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RemoveFunc(ctx, id)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedLoginService.RemoveCalls())
func (mock *LoginServiceMock) RemoveCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *LoginServiceMock) Save(ctx context.Context, data client.LoginData) error {
	callInfo := struct {
		Ctx  context.Context
		Data client.LoginData
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	if mock.SaveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SaveFunc(ctx, data)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedLoginService.SaveCalls())
func (mock *LoginServiceMock) SaveCalls() []struct {
	Ctx  context.Context
	Data client.LoginData
} {
	var calls []struct {
		Ctx  context.Context
		Data client.LoginData
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
