// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/mkolibaba/gophkeeper/client"
	"sync"
)

// Ensure, that NoteServiceMock does implement client.NoteService.
// If this is not the case, regenerate this file with moq.
var _ client.NoteService = &NoteServiceMock{}

// NoteServiceMock is a mock implementation of client.NoteService.
//
//	func TestSomethingThatUsesNoteService(t *testing.T) {
//
//		// make and configure a mocked client.NoteService
//		mockedNoteService := &NoteServiceMock{
//			GetAllFunc: func(ctx context.Context) ([]client.NoteData, error) {
//				panic("mock out the GetAll method")
//			},
//			RemoveFunc: func(ctx context.Context, name string) error {
//				panic("mock out the Remove method")
//			},
//			SaveFunc: func(ctx context.Context, data client.NoteData) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedNoteService in code that requires client.NoteService
//		// and then make assertions.
//
//	}
type NoteServiceMock struct {
	// GetAllFunc mocks the GetAll method.
	GetAllFunc func(ctx context.Context) ([]client.NoteData, error)

	// RemoveFunc mocks the Remove method.
	RemoveFunc func(ctx context.Context, name string) error

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, data client.NoteData) error

	// calls tracks calls to the methods.
	calls struct {
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data client.NoteData
		}
	}
	lockGetAll sync.RWMutex
	lockRemove sync.RWMutex
	lockSave   sync.RWMutex
}

// GetAll calls GetAllFunc.
func (mock *NoteServiceMock) GetAll(ctx context.Context) ([]client.NoteData, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	if mock.GetAllFunc == nil {
		var (
			noteDatasOut []client.NoteData
			errOut       error
		)
		return noteDatasOut, errOut
	}
	return mock.GetAllFunc(ctx)
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedNoteService.GetAllCalls())
func (mock *NoteServiceMock) GetAllCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// Remove calls RemoveFunc.
func (mock *NoteServiceMock) Remove(ctx context.Context, name string) error {
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	if mock.RemoveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.RemoveFunc(ctx, name)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedNoteService.RemoveCalls())
func (mock *NoteServiceMock) RemoveCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *NoteServiceMock) Save(ctx context.Context, data client.NoteData) error {
	callInfo := struct {
		Ctx  context.Context
		Data client.NoteData
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	if mock.SaveFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SaveFunc(ctx, data)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedNoteService.SaveCalls())
func (mock *NoteServiceMock) SaveCalls() []struct {
	Ctx  context.Context
	Data client.NoteData
} {
	var calls []struct {
		Ctx  context.Context
		Data client.NoteData
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
